### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by seobink** [OliveOld/Documents#10]
Create applications using Android Studio

**Comment by seobink** [comment]
아.. 깃허브 넘나 어려운 것 ㅜㅜㅜ

**Comment by seobink** [comment]
# 안드로이드 개발 환경
0. 자바 JDK 설치: Java SE Development Kit 8
오라클 에서 설치: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

1. IDE 설치: Android Studio 2.2.3
안드로이드 스튜디오 설치 : https://developer.android.com/studio/index.html?hl=ko
```
Tip: 안드로이드 스튜디오 메모리 적게 잡아 먹는 법
C:\Program Files\Android\Android Studio\bin 들어가서
studio.exe 파일 메모장으로 연 뒤, 
(엑세스 권한이 없다고 하면 스튜디오 켜져있는 상태거나, 관리자 권한으로 실행할 것)
Xms256m  -> 128m
Xmx750m  -> 256m
변경 할 것!
ps. 궁극적인 방법이 아닌 임시조치, 그냥 사양 좋은 컴퓨터 구매해야함.
```

2. 안드로이드 SDK 설치
최소 SDK 버전: API 18: 4.3(Jelly Bean)
안드로이드 스튜디오에서 Tools>Android>SDK manager에서 설치가 가능.
책에서는 아래 나열 된 부분을 모두 설치 할 것을 권장하고 있음.
```
Tools>Android SDK Tools
Tools>Android SDK Platform-tools
Tools>Android SDK Build-tools
(가장 최신 버전의)Android 버전>SDK Platform
(가장 최신 버전의)Android 버전>ARM EABI v 7a System Image, Intel x86 Atom System Image
(가장 최신 버전의)Android 버전>Documentation for Android SDK
Extras>Android Support Repository
Extras>ANdroid Supoort Library
Extras>Google Repostitory
Extras>Google USB Driver
Extras>Intel x86 Emulator Accelerator
```

**Comment by seobink** [comment]
![GitHub Logo](/images/logo.png)
Format: ![Alt Text](url)

**Comment by 0n33y3d-z0mb13** [comment]
<안드로이드 - 블루투스 상세 설명>
https://developer.android.com/guide/topics/connectivity/bluetooth.html?hl=ko
http://hyoin1223.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D

**Comment by ghost** [comment]
https://github.com/pablobuenaposada/arduino-HC-06
-> java파일에 생기는 intelliJ 오류때문에 android studio에서는 실행되지않음
-> eclipse에서 실행

https://www.youtube.com/watch?v=r-ACBfG5fpM
-> 안드로이드 스튜디오에 있는 Bluetooth Chat코드
-> 코드 안드로이드 측에서 제공(https://github.com/googlesamples/android-BluetoothChat)
-> 양측에 해당 앱을 전부 설치하여야지 기기 인식이 가능함

블루투스 chat 예제

**Comment by everlong1992** [comment]
1. JDK
Java SE Development Kit 8u111(http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
2. Eclipse
Eclipse Neon(https://www.eclipse.org/downloads/download.php?file=/oomph/epp/neon/R2a/eclipse-inst-win64.exe)
3.ADT
Help> Install New Software
Name:ADT
Locaton:https://dl-ssl.google.com/android/eclipse/
4.SDK 알아서 설치

**Comment by 0n33y3d-z0mb13** [comment]
파일 저장
1. 참조
https://developer.android.com/training/basics/data-storage/files.html?hl=ko
2. 안드로이드 스튜디오 sqlite DB 조회를 위한 브라우저 사용하기  
http://mainia.tistory.com/4903

**Comment by 0n33y3d-z0mb13** [comment]
[발바닥아이콘.zip](https://github.com/OliveOld/Documents/files/760606/default.zip)

**Comment by seobink** [comment]
안드로이드 그래프 그리기
https://github.com/PhilJay/MPAndroidChart

**Comment by seobink** [comment]
SQLite 
http://kuroikuma.tistory.com/75

bluetooth connect
http://dsnight.tistory.com/44

파일 저장
http://kitesoft.tistory.com/44

**Comment by 0n33y3d-z0mb13** [comment]
# 블루투스 통신 테스트를 위한 아두이노 코드
기기명 GIGI1
비밀번호 0000

```
#include <SoftwareSerial.h>

SoftwareSerial swSerial(2, 3);

void setup(){  
   swSerial.begin(9600); 
}

/* 출력 함수 */
void print_swSerial1()
{
    swSerial.print(0.11);
    swSerial.print(", ");
    swSerial.print(0.12);
    swSerial.print(", ");
    swSerial.print(0.13);
    swSerial.print(", ");
    swSerial.print(0.14);
    swSerial.print(", ");
    swSerial.print(0.15);
    swSerial.print(", ");
    swSerial.print(0.16);
    swSerial.print("\n");
}

void print_swSerial2()
{
    swSerial.print(0.21);
    swSerial.print(", ");
    swSerial.print(0.22);
    swSerial.print(", ");
    swSerial.print(0.23);
    swSerial.print(", ");
    swSerial.print(0.24);
    swSerial.print(", ");
    swSerial.print(0.25);
    swSerial.print(", ");
    swSerial.print(0.26);
    swSerial.print("\n");
}

void print_swSerial3()
{
    swSerial.print(0.31);
    swSerial.print(", ");
    swSerial.print(0.32);
    swSerial.print(", ");
    swSerial.print(0.33);
    swSerial.print(", ");
    swSerial.print(0.34);
    swSerial.print(", ");
    swSerial.print(0.35);
    swSerial.print(", ");
    swSerial.print(0.36);
    swSerial.print("\n");
}

void loop() 
{
   print_swSerial1();
   delay(100);
   print_swSerial2();
   delay(100);
   print_swSerial3();
   delay(100);
}
```

**Comment by 0n33y3d-z0mb13** [comment]
에뮬 아닌 실제 폰에서 DB 확인 시 - http://ssscool.tistory.com/entry/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4Android-Studio-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-%EB%94%94%EB%B0%94%EC%9D%B4%EC%8A%A4-%ED%85%8C%EC%8A%A4%ED%8A%B8%ED%95%A0-%EB%95%8C-SQLite-DB-File-%EA%B2%BD%EB%A1%9C-DataData%ED%8C%A8%ED%82%A4%EC%A7%80%EB%AA%85%EC%97%90-DB%ED%8C%8C%EC%9D%BC%EC%9D%84-%EC%B0%BE%EC%9D%84-%EC%88%98-%EC%97%86%EC%9D%84-%EB%95%8C-%ED%95%B4%EA%B2%B0%EB%B0%A9%EB%B2%95-%EB%94%94%EB%B0%94%EC%9D%B4%EC%8A%A4-DB-%ED%8C%8C%EC%9D%BC-%EC%B0%BE%EA%B8%B0-%EB%94%94%EB%B0%94%EC%9D%B4%EC%8A%A4-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B2%A0%EC%9D%B4%EC%8A%A4-%ED%8C%8C%EC%9D%BC-%EC%B0%BE%EA%B8%B0
안드로이드 이미지 가져와서 ImageView에 보이기 - http://jeongchul.tistory.com/287

**Comment by 0n33y3d-z0mb13** [comment]
SQLite 자료형

사용할 수 있는 자료형은 5가지 

NULL: 널값

INTEGER: 1,2,3,4,6,8bytes의 정수값
(자동증가 시킬 경우 INTEGER PRIMARY KEY AUTOINCREMENT 로 표기)

REAL: 8bytes의 부동소수점값

TEXT: UTF-8, UTF-16BE, UTF-16LE인코딩의 문자열

BLOB: 입력된 그대로 저장, 바이너리 파일 등

다른 형태는 어떻게 만들면 될까? 

Boolean타입: INTEGER로 만들어서 0과 1로 구별.

Date, Time타입
      TEXT: YYYY-MM-DD HH:MM:SS.SSS 형태로 저장
      REAL: 율리우스력을 기준으로 하는 정보를 저장
      INTEGER: UTC타입으로 저장

SQLite에 숫자, 문자, 바이너리를 넣을 수 있으니 자유롭게 넣고 개발자가 알아서 정해서 사용하면 된다.

SQLite는 대용량의 데이터를 처리하기에는 적합하지 않기에 대형프로그램보다는 지금 가장 많이 사용되고 있는 안드로이드 어플 개발 등 작은 프로그램 개발에 사용된다. 즉 다수의 개발자가 아닌 소수 혹은 혼자서 개발하는 경우가 많을 것이기에 좀 더 가볍고 자유롭게 사용할 수 있게 하는 편이 더 낫다.



출처 : http://redroid.tistory.com/1
