### ISSUE TITLE
실험 및 실험결과

### ISSUE THREAD

**Issue by 0n33y3d-z0mb13** [OliveOld/Documents#13]
# 2017/01/08
<테스트>
실험자: 김서빈
실험 장소: 집 
실험 대상: 코카스파니엘 , 11개월 , 높이 50cm, 길이 54cm, 11kg
제품 부착 위치 및 방향(그림으로 그려주세요):
특이사항: 가속도계 값만 데이터 처리. 원래 값에는 gyro 값도 있으나 오차가 커 보여서 일단은 가속도계 값만 그래프로 그려 봄. 자이로 값은 나중에 오차가 어떻게 발생하는지 확인 해 보겠음.

**Comment by 0n33y3d-z0mb13** [comment]
# 가만히 있음>rest
1. **실험 시간**(start: 2017-01-08 16:11:47 473232, end: 2017-01-08 16:13:13 787363)

2. **추출 데이터**:
[20170108_161147_rest_accel.txt](https://github.com/OliveOld/Documents/files/692968/20170108_161147_rest_accel.txt)
[20170108_161147_rest_gyro.txt](https://github.com/OliveOld/Documents/files/692967/20170108_161147_rest_gyro.txt)


3. **그래프 변환**
**Accel**
![graph](https://cloud.githubusercontent.com/assets/21700941/21749100/10dcae3a-d5da-11e6-8158-fa2aa7b1fa3c.PNG)
위 텍스트 파일로 추출한 그래프의 모습. 범례는 위로부터 x, y, z를 의미
x축은 데이터의 수, y축은 그냥 가속도계의 출력 값 (이 값들은 아직 유의미한 값이 아님. 여기서 중력가속도를 곱해야 각 축의 가속도 값을 의미하게 되는 것으로 알려져 있음)
동영상을 본 결과, 정확하게 맞지는 않지만 가장 앞쪽의 평평한 부분은 강아지가 가만히 있는 것으로 보이고그 다음 급격한 변화는 실험자가 손으로 센서를 만지는 것 같음. 중간에 조금 가만히 있다가, 고개를 약간 뒤척이는 모습이 가장 마지막 부분인 것으로 보인다.
  **Gyro**
        
   ![rest-gyro](https://cloud.githubusercontent.com/assets/16562932/21838384/035cbe8e-d815-11e6-9e38-8e5ec9e01b5c.png)


4. **실험 모습** : 휴식하는 개의 모습
![_](https://cloud.githubusercontent.com/assets/21700941/21749103/14d3e850-d5da-11e6-8040-0c62ab21baa3.PNG)

**Comment by 0n33y3d-z0mb13** [comment]
# 가만히 있음>Sleep1
1. **실험시간**(start: 2017-01-08 16:16:16 882424, end: 2017-01-08 16:17:35 553001)

2. **추출 데이터**: 
[20170108_161616_sleep1_accel.txt](https://github.com/OliveOld/Documents/files/692993/20170108_161616_sleep1_accel.txt)
[20170108_161616_sleep1_gyro.txt](https://github.com/OliveOld/Documents/files/692992/20170108_161616_sleep1_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sleep1](https://cloud.githubusercontent.com/assets/21700941/21749807/0e841e4c-d5ea-11e6-8834-14e87f84a72e.PNG)
범례 및 x,y축은 위 실험과 동일. 초반에 머리를 바닥에 대고 가만히 누워 있다가 그래프가 움직이는 시점에서는 머리를 들고 앉아있음. 후반에는 다시 머리를 두고 누움.
   **Gyro**
   ![sleep1-gyro](https://cloud.githubusercontent.com/assets/16562932/21761101/1e0e7e0c-d694-11e6-9e6d-fbf2063f47d0.png)


4. **실험 모습**
![img_sleep1](https://cloud.githubusercontent.com/assets/21700941/21749825/a4182ac0-d5ea-11e6-9298-8c1f51c12157.PNG)
![img_sleep1_2](https://cloud.githubusercontent.com/assets/21700941/21749826/a778c5da-d5ea-11e6-9b5e-4aae58992f43.PNG)
자세가 변화되고 있다.

**Comment by 0n33y3d-z0mb13** [comment]
# 가만히 있음>Sleep2
1. **실험시간**: (start: 2017-01-08 16:13:43 457324, end: 2017-01-08 16:14:10 522596)

2. **추출 데이터**(gyro 제외): 
[20170108_161343_sleep2_accel.txt](https://github.com/OliveOld/Documents/files/693012/20170108_161343_sleep2_accel.txt)
[20170108_161343_sleep2_gyro.txt](https://github.com/OliveOld/Documents/files/693013/20170108_161343_sleep2_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sleep2](https://cloud.githubusercontent.com/assets/21700941/21749840/ecf9e210-d5ea-11e6-96e8-cf3ceb58cca9.PNG)
실험 시간 약 30초 동안 미동 없이 누워 있는 모습
**Gyro**
![sleep2-gyro](https://cloud.githubusercontent.com/assets/16562932/21761351/bd375ff2-d695-11e6-9eb6-70c5f14902c0.png)

4. **실험 모습**
![img_sleep2](https://cloud.githubusercontent.com/assets/21700941/21749849/0f5a73c4-d5eb-11e6-9302-4eb1aa057b0c.PNG)
위와 같은 모습으로 30초간 센서 데이터를 획득

**Comment by 0n33y3d-z0mb13** [comment]
# Sit1
1. **실험 시간**: (start: 2017-01-08 15:46:20 726295, end: 2017-01-08 15:46:56 556337)

2. **추출 데이터**: 
[20170108_154620_sit1_accel.txt](https://github.com/OliveOld/Documents/files/692889/20170108_154620_sit1_accel.txt)
[20170108_154620_sit1_gyro.txt](https://github.com/OliveOld/Documents/files/692890/20170108_154620_sit1_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sit1](https://cloud.githubusercontent.com/assets/21700941/21750191/c8afea16-d5f0-11e6-97bc-9c809558c5fd.PNG)
**Gyro**
![sit1-gyro](https://cloud.githubusercontent.com/assets/16562932/21759932/90e0952c-d68b-11e6-8cda-453c4be196dd.png)

4. **실험 모습**
![img_sit1](https://cloud.githubusercontent.com/assets/21700941/21750199/14b77cee-d5f1-11e6-8af9-b643887a80ca.PNG)
![img_sit1_2](https://cloud.githubusercontent.com/assets/21700941/21750200/18b5c4b8-d5f1-11e6-944f-69693a4bdcb7.PNG)
위와 같은 모습으로 자세 변환됨

**Comment by 0n33y3d-z0mb13** [comment]
# Sit2
1. **실험 시간**: start: 2017-01-08 15:47:52 434329, end: 2017-01-08 15:48:21 889068

2. **추출 데이터**: 
[20170108_154752_sit2_accel.txt](https://github.com/OliveOld/Documents/files/692912/20170108_154752_sit2_accel.txt)
[20170108_154752_sit2_gyro.txt](https://github.com/OliveOld/Documents/files/692913/20170108_154752_sit2_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sit2](https://cloud.githubusercontent.com/assets/21700941/21750207/512ab2d6-d5f1-11e6-81a1-8cfbba0b17ec.PNG)
**gyro**
![sit2-gyro](https://cloud.githubusercontent.com/assets/16562932/21760094/cb89ad02-d68c-11e6-8a85-e4ebb76bbf39.png)

4. **실험 모습**
![img_sit2](https://cloud.githubusercontent.com/assets/21700941/21750213/71b32cae-d5f1-11e6-81ae-d68ab8b39e00.PNG)
영상에 따르자면 위와 같은 모습으로 앉았다 일어나기를 3번 반복함

**Comment by 0n33y3d-z0mb13** [comment]
# Sit3
1. **실험 시간**: start: 2017-01-08 15:47:04 963043, end: 2017-01-08 15:47:32 652028

2. **추출 데이터**:
[20170108_154704_sit3_accel.txt](https://github.com/OliveOld/Documents/files/692920/20170108_154704_sit3_accel.txt)
[20170108_154704_sit3_gyro.txt](https://github.com/OliveOld/Documents/files/692921/20170108_154704_sit3_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sit3](https://cloud.githubusercontent.com/assets/21700941/21750221/b010a8c8-d5f1-11e6-8d84-a515f4adbb6f.PNG)
**Gyro**
![sit3-gyro](https://cloud.githubusercontent.com/assets/16562932/21760210/ab565ac0-d68d-11e6-82d7-42e8b0025abe.png)

4. **실험 모습**
![img_sit3_1](https://cloud.githubusercontent.com/assets/21700941/21750230/e8ddd752-d5f1-11e6-9e54-1794e72b5741.PNG)
![img_sit3_2](https://cloud.githubusercontent.com/assets/21700941/21750231/e8e0140e-d5f1-11e6-8865-0046ec9a7c31.PNG)
영상에 따르자면 위와 같이 서 있음 -> 누워 있음 -> 앉아 있음으로 자세 변환됨.

**Comment by 0n33y3d-z0mb13** [comment]
# Sit4
1. **실험 시간**: start: 2017-01-08 15:45:22 676308, end: 2017-01-08 15:45:35 098882

2. **추출 데이터**: 
[20170108_154522_sit4_accel.txt](https://github.com/OliveOld/Documents/files/692931/20170108_154522_sit4_accel.txt)
[20170108_154522_sit4_gyro.txt](https://github.com/OliveOld/Documents/files/692948/20170108_154522_sit4_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_sit4](https://cloud.githubusercontent.com/assets/21700941/21750237/25fff5fc-d5f2-11e6-8a50-298ea1436e15.PNG)
**Gyro**
![sit4-gyro](https://cloud.githubusercontent.com/assets/16562932/21760623/cd385cbc-d690-11e6-9447-5562b409f992.png)

4. **실험 모습**
영상에 따르자면, 강아지가 앉아 있다가 어딘가로 뛰어 오르는 모습을 확인 할 수 있음.

**Comment by 0n33y3d-z0mb13** [comment]
# Walk
1. **실험 시간**: start: 2017-01-08 15:42:34 847238, end: 2017-01-08 15:43:24 060381

2. **추출 데이터**:
[20170108_154234_walk_accel.txt](https://github.com/OliveOld/Documents/files/692941/20170108_154234_walk_accel.txt)
[20170108_154234_walk_gyro.txt](https://github.com/OliveOld/Documents/files/692950/20170108_154234_walk_gyro.txt)

3. **그래프 변환**
**Accel**
![graph_walk](https://cloud.githubusercontent.com/assets/21700941/21750251/60069a76-d5f2-11e6-8fb3-dd05d59b1b3b.PNG)
**Gyro**
![walk-gyro](https://cloud.githubusercontent.com/assets/16562932/21760631/e1c01ed6-d690-11e6-95a1-dc662b80def0.png)

4. **실험 모습**
![img_walk](https://cloud.githubusercontent.com/assets/21700941/21750264/9085458a-d5f2-11e6-80cc-e9dd096c38f6.jpg)
강아지가 위와 같은 모습으로 보행함

**Comment by seobink** [comment]
@everlong1992  다음 측정시에는 짧막짧막하게 데이터를 측정하겠습니다. 
데이터 측정은

1. 앉기
2. 엎드리기
3. 뛰기
4. 걷기
5. 먹기

이렇게 총 다섯종류로 나누어 측정하겠습니다.
원하는 동작이 있으면 코멘 부탁욤

**Comment by 0n33y3d-z0mb13** [comment]
@seobink 먹기 까지는 안해도 괜찮을 것 같고, 앉기, 엎드리기, 걷기, 뛰기 네 동작 테스트를 각 5번 정도 수행하는 것이 좋을 것 같습니다. 
- 되도록이면 블루투스 데이터 수신 시작과 같은 시간에 촬영 시작, 종료
- 실험 전 주위 물건을 치우기
- 실험자가 강아지를 건드리지 않기
두분이서 실험은 벅찬 것 같고 제가 한번 가서 삼각대와 디지털 카메라를 설치 후 실험하는 것이 더 정확 할 것 같습니다. 코드가 더 다듬어 지면 제가 한번 방문하겠습니다. 수고하셨어요

**Comment by luncliff** [comment]
실험 내용이 많아질 것 같으니 차후에 저장소로 내용을 옮기는 것이 좋을 것 같습니다. 수고하셨습니다.

**Comment by 0n33y3d-z0mb13** [comment]
# 동하씨 실험 건(2017-01-17~18)
데이터 파일
[lie_원본.txt](https://github.com/OliveOld/Documents/files/713360/lie_.txt)
[lie_a.txt](https://github.com/OliveOld/Documents/files/713361/lie_a.txt)
[lie_g.txt](https://github.com/OliveOld/Documents/files/713362/lie_g.txt)

그래프
<가속도>
![lie_a](https://cloud.githubusercontent.com/assets/21700941/22056748/f00e0a3c-dda4-11e6-9108-b7c578f7f276.PNG)
<gyro>
![lie_g](https://cloud.githubusercontent.com/assets/21700941/22056744/edc3a778-dda4-11e6-94ab-632380b48971.PNG)

**Comment by ghost** [comment]
# 동하씨 실험 건(2017-01-17~18)

데이터 파일
[walk1a.txt](https://github.com/OliveOld/Documents/files/718500/walk1a.txt)
[walk1g.txt](https://github.com/OliveOld/Documents/files/718501/walk1g.txt)
[walk1.txt](https://github.com/OliveOld/Documents/files/718502/walk1.txt)


그래프
#가속도
![1](https://cloud.githubusercontent.com/assets/16562932/22137352/e5b53bb2-df1d-11e6-8812-ef8c25b93763.png)


#Gyro
![19](https://cloud.githubusercontent.com/assets/16562932/22137573/3bfc8042-df1f-11e6-9504-ae5a518d88c1.png)




데이터 파일
[sit2a.txt](https://github.com/OliveOld/Documents/files/718504/sit2a.txt)
[sit2g.txt](https://github.com/OliveOld/Documents/files/718506/sit2g.txt)
[sit2.txt](https://github.com/OliveOld/Documents/files/718505/sit2.txt)


그래프
#가속도
![17](https://cloud.githubusercontent.com/assets/16562932/22137410/4204a236-df1e-11e6-91d6-e16e17af12e0.png)

#Gyro
![18](https://cloud.githubusercontent.com/assets/16562932/22137459/9cd35d7e-df1e-11e6-91bd-5d85c343b5f6.png)

**Comment by 0n33y3d-z0mb13** [comment]
2017-01-17일에 진행한 실험에 대하여 결과 자료를 엑셀 파일로 만들었습니다.
동영상 및 원본 파일, 결과 파일은 구글 드라이브(pets_test_3)에서 확인하실 수 있습니다.
매트랩 체험판이 만료되어서 엑셀을 사용하였는데, 이 편이 더 편리 한 것 같습니다. 실험 결과를 내실 분은 http://physlab.snu.ac.kr/newphyslab/excel/excel.htm를 참고하시는것이 좋을 것 같습니다.

**Comment by luncliff** [comment]
현재 작성중인 코드를 Weka ARFF로 변경하는 코드를 작성하는 중인데, 버그를 수정하는데 시간 소모가 길어 생각보다 지연되고 있습니다. 죄송합니다. 

이번 주말 중으로 업데이트를 할 수 있도록 하겠습니다 :(

**Comment by seobink** [comment]
안드로이드 블루투스 데이터 전송 어플리케이션 제작 했습니다.
소스코드는 PetTrack_Android에 업데이트 했습니다.

오류 발견시 알려주시면 감사하겠습니다
