### ISSUE TITLE
안드로이드 진행

### ISSUE THREAD

**Issue by chorok** [OliveOld/Documents#16]
[안드로이드 독학 일지_정초록.pdf](https://github.com/OliveOld/Documents/files/753559/_.pdf)

[draft (2).zip](https://github.com/OliveOld/Documents/files/753561/draft.2.zip)

**Comment by chorok** [comment]
소스코드는 용량이 너무 커서 카톡으로 전송했습니다

**Comment by 0n33y3d-z0mb13** [comment]
1. 진행 하신대로 scrollview를 사용하시는게 맞는 것 같습니다. 굳이 한 화면에 들어오게 하려면 Date Picker를 좀 작고 평평한 느낌의 Horizontal Date picker를 사용 해 보는 건 어떨까요? 아래 페이지에서 라이브러리를 다운받아 사용 할 수 있습니다.
(예를 들면: https://raghuforpm.wordpress.com/2015/03/06/custom-horizontal-date-picker-in-android/, http://www.appance.com/horizontaldatepicker/)

 2. px단위 대신 dp를 사용하시는게 맞습니다만 굳이 세세하게 맞춰가며 사용하실 필요가 없을 것 같다는것이 의견입니다. 일일히 화면 크기에 맞춰보고 싶으시면 px/dp 계산기를 사용하거나 아니면 매번 dp를 변경하며 디자인 탭에서 확인하면 될 것 같습니다. 

3. 진행하신 대로 나머지 액티비티도 만들어 나가시면 될 것 같습니다.

**Comment by 0n33y3d-z0mb13** [comment]
안드로이드 관련 내용은 petrack_android 이슈에 달도록 하겠습니다
