### ISSUE TITLE
소형화센서

### ISSUE THREAD

**Issue by seobink** [OliveOld/Documents#18]
http://x-io.co.uk/ngimu/

IMU + Bluetooth + SD 카드 + 스트랩
가격 : 310파운드

https://www.lp-research.com/lpms-b2/
- 기능
IMU / AHRS / Motion Sensor with Bluetooth 2.1 and 4.1
- Product type 
 LPMS-B2, LPMS-B2 OEM 
- Size 
 LPMS-B2: 39 x 39 x 8 mm
 LPMS-B2 OEM: 16 x 31 x 4 mm 
- Weight 
 LPMS-B2: 12 g
 LPMS-B2 OEM: 2 g 
- 가격
 협상

**Comment by 0n33y3d-z0mb13** [comment]
1. Microduino+ core

2. Light blue bean
1) 가격 
Order 4+ Beans and receive 1 Free Maker Kit per order.
4 Beans	$28.50 per Bean => 즉 5개에 12만원정도
2) 3축 가속도, 저전력 블루투스 포함
(https://store.punchthrough.com/collections/bean-family/products/lightblue-bean-plus?_ga=1.105731331.1230759921.1489140829)




비교--
https://www.google.co.kr/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwjx38WN2svSAhVJkJQKHTAbBGwQjRwIBw&url=http%3A%2F%2Ffabricatethings.dothome.co.kr%2Flight-blue-bean%2F&psig=AFQjCNGUsGPvua8gWl9l9cbT5RN2_gcOMg&ust=1489227177935758

**Comment by seobink** [comment]
https://www.dfrobot.com/product-1259.html
https://www.eleparts.co.kr/EPXFG7KL

블루 + 나노
- 가격 : 14.90달러
- Size：28.8mm X 33.1mm(1.13" x 1.30")
- Weight：10g

http://www.twiz.io/
블루+IMU 
- 2.4 cm x 2.4 cm (< 1 inch), 1.1cm thick (< ½ inch), 4.6g (~7.6g w/ battery
- 판매하고 있는 사이트는 따로없음 , 우선 메일을 보내놓았음


https://www.seeedstudio.com/Seeed-Tiny-BLE-BLE-%2B-6DOF-Mbed-Platform-p-2268.html
http://vctec.co.kr/product/%EC%8B%9C%EB%93%9C-tiny-ble-%EC%97%A0%EB%B2%A0%EB%93%9C-%ED%94%8C%EB%9E%AB%ED%8F%BC-%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A440-6dofseeed-tiny-ble-ble-6dof-mbed-platform/5452/
블루 + 6DOF Mbed Platform
- 가격 : $24.00
- MPU-6050:3d accelemeter + 3d gyroscope
- Power supply:USB/battery(3.5-4.2V)
- 크기 : 43.3mm x 29.0mm x 4.3mm


http://daduino.co.kr/product/detail.html?product_no=1058&cate_no=25&display_group=1
블루 + 아두이노
- 가격 : 38,000원
- SRAM : 2.5k / EEPROM : 1k / Flash Memory : 32KB 


https://www.tindie.com/products/femtoduino/femtobeacon-kit-basic/
- ...???


p.s 아두이노+블루 통합 센서에 IMU센서를 합치는 것도 나쁘지 않을 것 같습니다.
그리고 저희 자이로 말고 엑셀만 사용할건가요..?(그렇게 되면 사용가능한 센서 범위가 넓어질것같아요)

**Comment by seobink** [comment]
http://mechasolution.com/shop/goods/goods_view.php?goodsno=329628&category=117001002

    아두이노 호환
    8개의 GPIO
    블루투스 4.0 (BLE)
    무선 프로그래밍
    3축 가속도 센서 모듈
    온도 센서 내장
    RGB LED
    CR2032 동전 배터리
    ATmega328p 마이크로컨트롤러 8MHz
    3V 동작 전압
    6개의 디지털 입출력
    2개의 아날로그 입력 (10비트)
    PWM 핀 (4개)
    1개의 SPI 포트
    1개의 I2C 포트

**Comment by chorok** [comment]
1. 릴리 + 블루투스
https://www.sparkfun.com/products/13633
2. 릴리 + sd카드 연결부
https://www.sparkfun.com/products/11013

의견
1. 패드+Imu+블루투스+배터리 모두 합쳐진건 없는것 같음
2. 해외사이트 구매시 분명 신용카드로 결제해야할텐데 그 경우 지원금 사용 불가능

**Comment by 0n33y3d-z0mb13** [comment]
1. 블루투스 내장 보드에 센서 추가

2. 릴리패드에 각 모듈 추가
  - http://mechasolution.com/shop/goods/goods_list.php?&category=117004
  - CR2032 릴리패드 코인셀 배터리홀더 스위치 포함 / LilyPad Coin Cell Battery Holder - Switched - 20mm
5,500원
 - 릴리패드 BLE 아두이노 호환 메인보드 / 아두이노 프로그래밍 / 블루투스4.0 /Lilypad Simblee BLE Board - RFD77101 
 - 릴리패드 가속도센서 ADXL335 / LilyPad Accelerometer ADXL335

3. Light Blue Bean(가속도 센서만 존재)에 IMU추가 + sd카드 모듈 추가
- http://mechasolution.com/shop/goods/goods_view.php?goodsno=329628&category=117001
- SD카드 리더 모듈 (Arduino SDCard Reader Module) / SD Card Reader (http://mechasolution.com/shop/goods/goods_view.php?goodsno=412&category=132024)
