### ISSUE TITLE
문헌 조사

### ISSUE THREAD

**Issue by luncliff** [OliveOld/Documents#2]
참고문헌 또는 기술자료와 관련된 이슈는 이쪽으로 모으겠습니다. 

RISS를 통해서 현재 2개의 논문을 신청하였으며, 각각은 다음과 같습니다. 상세한 내용은 확인하지 않은 상태이며, 보다 적합한 내용을 찾으면 교체하도록 하겠습니다.

 - [Implementation of a real-time human movement classifier using a triaxial accelerometer for ambulatory monitoring](http://ieeexplore.ieee.org/document/1573717/?arnumber=1573717)
 - [Ambulatory system for human motion analysis using a kinematic sensor: monitoring of daily physical activity in the elderly](http://ieeexplore.ieee.org/document/1203810/?arnumber=1203810&tag=1). June 2003. IEEE. B. Najafi, K. Aminian, A. Paraschiv-Ionescu

**Comment by chorok** [comment]
[반려견의 생활환경이 비만에 미치는 요인에 관한 연구.pdf](https://github.com/OliveOld/Wiki/files/587092/default.pdf)
[IMU 기반 웨어러블 디바이스를 활용한 반려견의 행동 인지 실험.pdf](https://github.com/OliveOld/Wiki/files/587094/IMU.pdf)

**Comment by chorok** [comment]
[스마트폰 분실방지 어플리케이션에 대한 연구.pdf](https://github.com/OliveOld/Wiki/files/587096/default.pdf)

**Comment by luncliff** [comment]
@chorok 감사합니다 초록씨. Download 가 가능하도록 되어있으니 편리하군요.
