### ISSUE TITLE
가속도/자이로 센서 프로그래밍

### ISSUE THREAD

**Issue by luncliff** [OliveOld/Documents#4]
### To Do
 - 가속도 센서 프로그래밍
 - 자이로 센서 프로그래밍
 - 데이터 받아서 연산처리하기
   - 적분
   - 변위 계산

**Comment by tayeon1212** [comment]
http://www.jkelec.co.kr/img/sensors/manual/mpu9250_gy9250/mpu9250_gy9250_manual.html

**Comment by 0n33y3d-z0mb13** [comment]
시리얼 모니터에 출력되는 값을 그래프로 그려주는 프로그램입니다.
https://code.google.com/archive/p/serialchart/
프로그램의 사용법 pdf입니다.
http://realsys.co.kr/data/hobby/7.%EC%8B%9C%EB%A6%AC%EC%96%BC%EA%B7%B8%EB%9E%98%ED%94%84pdf.pdf

**Comment by ghost** [comment]
http://www.jkelec.co.kr/img/sensors/manual/mpu9250_gy9250/mpu9250_gy9250_manual.html

-> 가속도 센서, 자이로 센서의 데이터 값을 출력해주는 코드입니다. 예쁘게 출력해주는 코드입니다.
(가속도, 자이로 센서값 출력)


http://blog.naver.com/msyang59/220676309696
-> 안 예쁘게 출력해주는 코드 입니다. 
(가속도 출력)

**Comment by luncliff** [comment]
Using the MPU9250 to get Real-time Motion Data. GPL3+
https://create.arduino.cc/projecthub/paulplusx/using-the-mpu9250-to-get-real-time-motion-data-08f011?ref=search&ref_id=IMU 9250&offset=0

**Comment by luncliff** [comment]
앞서 제가 작성한 To Do List는 결국 데이터값을 출력해서 보여주는 부분으로 종합될 수 있을 것 같습니다. 정기 회의때 한번 더 논의 하고 To Do를 갱신하도록 하겠습니다.

특히 Serial chart는 세팅 방법을 저도 알아둬야 할 것 같네요.

**Comment by ghost** [comment]
https://github.com/orgua/iLib
-> IMU센서를 참고한 라이브러리 입니다

**Comment by 0n33y3d-z0mb13** [comment]
Serial Chart의 Configuration은 다음과 같은 포맷으로 작성하면 됩니다.

```
[_setup_]
port=COM3
baudrate=115200

width=1000
height=200
background_color=white

grid_h_origin =100
grid_h_step=10
grid_h_color=#EEE
grid_h_origin_color=#CCC
grid_v_origin=0
grid_v_step=10
grid_v_color=#EEE
grid_v_origin_color=transparent

[_default_]
min=-200
max=200

[interval]
color=transparent
min=0
max=100000

[Field1]
color=red

[Field2]
color=blue

[Field3]
color=green
```

**Comment by ghost** [comment]
상보필터, 칼만필터

**Comment by 0n33y3d-z0mb13** [comment]
# 필터
http://daddynkidsmakers.blogspot.kr/2015/09/complementary-filter-imu.html 이곳에서 상보 필터에 대하여 간단히 설명하고 있습니다. 상보 필터의 상세한 코드도 포함되어 있구요, 글 아래에 칼만 필터 대신 상보 필터를 사용하는 이유를 다음과 같이 써놓고 있습니다.
상보 필터는 칼만 필터에 비해, **간단하며,** 아두이노와 같은 **저성능 보드에서도 잘 동작하는 가벼운 알고리즘이다.**
=> 수식 포함되어 있습니다.

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/16562932/20957763/020ef4ac-bc95-11e6-90da-173a2499f7d1.png)

**Comment by 0n33y3d-z0mb13** [comment]
# MPU-9250 Manual
- 제이케이이엠씨(JK EMC)에서 제공하는 MPU-9250 센서 메뉴얼입니다.(한글) :  http://www.jkelec.co.kr/img/sensors/manual/mpu9250_gy9250/mpu9250_gy9250_manual.html
- MPU-9250 Product Specification Revision 1.0(영문): https://store.invensense.com/datasheets/invensense/MPU9250REV1.0.pdf
- position and orientation determination of a probe with use of the Imu: [MPU9250 필터 등 설명.pdf](https://github.com/OliveOld/Wiki/files/636284/MPU9250.pdf)

**Comment by ghost** [comment]
# 그래프 프로그램
- Graphite: https://graphiteapp.org/#gettingStarted
- RRdTool: http://www.solanara.net/solanara/rrdtool

**Comment by luncliff** [comment]
http://www.starlino.com/imu_guide.html

**Comment by 0n33y3d-z0mb13** [comment]
# Example Code
- **mpu9250센서의 raw값 출력** : [mpu9250_raw.zip](https://github.com/OliveOld/Wiki/files/636036/mpu9250_raw.zip)
- **칼만필터 적용 코드**: https://developer.mbed.org/users/onehorse/code/MPU9250AHRS/file/4e59a37182df/MPU9250.h
- **상보필터 적용 코드?**: http://thinkslowly.tistory.com/37

**Comment by 0n33y3d-z0mb13** [comment]
# 12-07
 
1. 한 것
- sketch의 시리얼 플로터로 그래프 확인
- raw 값 출력

2. 진행 해야 할 것
- 오차를 확인하고 싶은데 어떻게 확인해야 할지 모르겠음
- 상보필터를 적용 한 MPU9250 코드를 아직 돌려보지 못했음
- 진행 한 것에 HC-06 적용하여 해당 값들을 컴퓨터로 보내서 이것을 그래프로 표시하는 프로그램 다시 알아봐야 할 것 같음

**Comment by ghost** [comment]
Tli에서 추천해주신 그래프 툴 설명서입니다. - MATLAB

http://web.yonsei.ac.kr/hgjung/Lectures/PME306/B2.%20MATLAB%20%EA%B8%B0%EC%B4%88%20%EC%82%AC%EC%9A%A9%EB%B2%95.pdf
