### ISSUE TITLE
통신 프로그래밍

### ISSUE THREAD

**Issue by luncliff** [OliveOld/Documents#5]
### To Do
 - Bluetooth 프로그래밍
 - 현재 사용하는 모듈의 특징 정리
   - 전송가능한 데이터 속도 (Data Rate): 최대, 평균, 최소
   - 전력 소모량
   - 활동 제약 정리(Master Device와의 거리 등) 
 - 서적? Guide 자료 확인
 - 외부 라이브러리 조사

**Comment by seobink** [comment]
넹넹

**Comment by seobink** [comment]
http://dev.re.kr/38

**Comment by seobink** [comment]
🎱 **블루투스 연결**

👍  오늘 한 일 

- 블루투스 이름, PINnum 변경
   name : seobin
   PINnum : 0421
- 안드로이드와 블루투스 연결 성공

👎  해결해야할 것
안드로이드와 블루투스는 페어링 되나, 데이터 전송이 되지 않는다... ㅠㅠ




_참조한 사이트_
http://deneb21.tistory.com/267 - 안드로이드와 블루투스 페어링
http://m.blog.daum.net/nety2k/14070757 - LED 깜빡이기
http://dev.re.kr/38 - 문자열 주고 받기
https://github.com/ice3x2/HC-06_Arduino_Echo/blob/master/Arduino%20src/HC_06_Echo.ino



```c
#include <SoftwareSerial.h>
void setup() {
  Serial.begin(9600);
  pinMode(13, OUTPUT);
}

void loop() {
  if (Serial.available()){
    byte data;
    data = Serial.read();
    if(data=='a'){
      digitalWrite(13, HIGH);   // set the LED on
      //Serial.print("HIGH");
    }
    if(data=='b'){
      digitalWrite(13, LOW);    // set the LED off
     //Serial.print("LOW");
    }
  }
}
```

**Comment by luncliff** [comment]
문서 내용들을 모두 읽어봤습니다. 별다른 문제가 나오기 전까지는 Software Serial을 사용하면 될 것 같아 보입니다만, 데이터 송수신이 어떤방식인지 이해가 잘 되지 않네요. 
정기회의 때 여쭤보겠습니다.

 - Software Serial Interface
 - Native Serial과 Software Serial의 차이점?
 - 데이터 전송이 가능하다면, 어느정도? (Average Transmission Rate)

**Comment by chorok** [comment]
http://blog.naver.com/eduino/220858621071 아두이노 나노 설명

**Comment by seobink** [comment]
# **Bluetooth v4.0 and Bluetooth Low Energy**

Bluetooth 4.0 버전
  1. classic :  Bluetooth v2.1+EDR 과 v3.0+HS
  2. high-speed :  Bluetooth v2.1+EDR 과 v3.0+HS
**3. low-energy (실제 Bluetooth v4.0 표준은 Bluetooth low energy (BLE) 임 )**

BLE는 신호 도달 거리 "100m –> 50m"으로 단축
 데이터 전송 속도 "0.7-2.1 Mbps –> 0.27 Mbps" 으로 낮춤
 -> 전력 소모를 줄임

 
> BLE 는 배터리에 의존하면서 빠른 전송 속도와 연결의 지속성을 요하지 않는 주변 장치(센서 장치)에 적합 

스마트 워치, 스마트 밴드 및 각종 휴대용 장치에 광범위하게 사용중

**Comment by seobink** [comment]
To 민지브로
널 닮은 사진을 찾았어

![comm](http://i.imgur.com/4lzAh1g.jpg)

**Comment by seobink** [comment]
## Bluetooth Classic 	Bluetooth 4.0 Low Energy (BLE) 	ZigBee 	WiFi 의 스펙비교

|Name | Bluetooth Classic  |	Bluetooth 4.0 Low Energy (BLE) |	ZigBee |	WiFi |
|:-----   |-----:|-----:|-----:|-----:|
IEEE Standard |	802.15.1 |	802.15.1 |	802.15.4 |	802.11 (a, b, g, n)|
Frequency (GHz) |	2.4 |	2.4 |	0.868, 0.915, 2.4 |	2.4 and 5|
Maximum raw bit rate (Mbps) 	|1-3 	|1 	|0.250 	|11 (b), 54 (g), 600 (n)|
Typical data throughput (Mbps) 	|0.7-2.1 	|0.27 	|0.2 	|7 (b), 25 (g), 150 (n)|
Maximum (Outdoor) Range (Meters) 	|10 (class 2), 100 (class 1) 	|50 	|10-100 	|100-250|
Relative Power Consumption |	Medium 	|Very low 	|Very low |	High|
Example Battery Life 	|Days 	|Months to years 	|Months to years 	|Hours|
Network Size| 	7 	|Undefined 	|64,000+ 	|255|

**Comment by seobink** [comment]
블루투스 관련 자료 링크
http://www.ktword.co.kr/abbr_view.php?m_temp1=1802 (정보통신기술용어해설)
https://namu.wiki/w/%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4 (나무위키)
https://ko.wikipedia.org/wiki/%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4 (위키파이)

**Comment by seobink** [comment]
블루투스 관련 자료 링크
http://www.ktword.co.kr/abbr_view.php?m_temp1=1802 (정보통신기술용어해설)
https://namu.wiki/w/%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4(나무위키)
https://ko.wikipedia.org/wiki/%EB%B8%94%EB%A3%A8%ED%88%AC%EC%8A%A4(위키파이)

**Comment by seobink** [comment]
🎱 블루투스 데이터 전송
   

👍 오늘 한 일
  - 안드로이드에서 블루투스로 데이터 전송
  - ( 영어 숫자 기호 전송 가능, 단 한국어는 인코딩문제해결해야할듯)

👎 해결해야할 것
  - 데이터 전송 한국어는 인코딩 문제
  - 그러나 한국어 전송할 일은 없을 것 같음

_참조한사이트_
http://deneb21.tistory.com/267

```c
#include <SoftwareSerial.h> //시리얼 통신 라이브러리 호출
 
int blueTx=2;   //Tx (보내는핀 설정)
int blueRx=3;   //Rx (받는핀 설정)
SoftwareSerial mySerial(blueTx, blueRx);  //시리얼 통신을 위한 객체선언
String myString=""; //받는 문자열
 
void setup() {
  Serial.begin(9600);   //시리얼모니터 
  mySerial.begin(9600); //블루투스 시리얼 개방
  pinMode(13, OUTPUT);  //Pin 13을 OUTPUT으로 설정 (LED ON/OFF)
}
 
void loop() {
  while(mySerial.available())  //mySerial 값이 있으면
  {
    char myChar = (char)mySerial.read();  //mySerial int형식의 값을 char형식으로 변환
    myString+=myChar;   //수신되는 문자열을 myString에 모두 붙임 (1바이트씩 전송되는 것을 모두 붙임)
    delay(5);           //수신 문자열 끊김 방지
  }
  
  if(!myString.equals(""))  //myString 값이 있다면
  {
    Serial.println("input value: "+myString); //시리얼모니터에 myString값 출력
 
      if(myString=="on")  //myString 값이 'on' 이라면
      {
        digitalWrite(13, HIGH); //LED ON
      } else {
        digitalWrite(13, LOW);  //LED OFF
      }
      
    myString="";  //myString 변수값 초기화
  }
}
```

**Comment by seobink** [comment]
## 보 레이트 [baud rate] (전자용어사전, 1995. 3. 1., 성안당)
데이터 통신에서 직렬 전송의 변조 속도를 1초간에 전송되는 신호의 수로 나타낸 값을 말한다. 단말 장치와 모뎀 간의 신호는 2치 신호이므로 신호 수와 비트 수는 일치하여 변조 속도와 전송 속도(1초간에 전송되는 비트 수로, 단위는 b/s)는 같다. 모뎀과 모뎀간에서는 신호는 2치 신호라고만은 할 수 없고, PSK 등에 의해서 다치화함으로써(1신호에 복수 비트를 싣는) 전송 효율을 높일 수 있다.

1. Bit Rate 와 Baud Rate 의 정의

1.1 Bit Rate 정의

비트 레이트 (Bit Rate) 는 초당 얼마나 많은 데이터 비트(‘1’ 또는 ‘0’) 를 전송할 수 있는가를 나타내는 말이다. 또 우리가 자주 쓰는 BPS 라는 말이 있는데 이는 Bit Per Second 로서 초당 보낼 수 있는 비트의 수를 나타낸다. 이는 모뎀의 전송속도를 측정하는 단위로 사용되어 졌다. 일반적으로 28,800 모뎀이라면 28,800bps 의 전송속도를 나타내는 것이다.

예를 들어, 2400bit/second(bps) 라면 초당 2400개의 비트 정보를 전달할 수 있다는 뜻이다. 이는 반대로 이야기하면 1 비트 정보를 보내기 위해서 416.6us 의 시간(1s/2400bit) 이 필요하다는 이야기이다.

1.2 Baud Rate

보 레이트 (Baud Rate) 는 초당 얼마나 많은 심볼(Symbol, 의미 있는 데이터 묶음) 을 전송할 수 있는가를 나타내는 말이다. 이는 이론적인 통신 단위로 초당 신호(Signal) 요소의 수를 나타낸다.

만약 하나의 신호요소가 2비트로 구성되어 있는 경우라면 보는 BPS 의 반이 된다. 즉, 1보 동안 2비트가 전송된다. 일반적으로 신호를 1비트로 여긴다면 BPS 와 같은 단위가 된다.

심볼이란 말은 의미 있는 데이터 비트의 묶음이다. 일반적으로 시리얼 통신에서는 데이터 비트가 8-bit 를 사용하므로 이를 하나의 심볼이라고 이야기 할 수 있다.

1개의 symbol (또는 character) 는 8개의 bit 정보와 같다.

예를 들어, 2400 baud rate 를 갖는다는 말은 1초에 2400개의 의미 있는 심볼 즉 캐릭터를 송신할 수 있다는 이야기이다. 1초에 2400개의 ASCII 코드를 전송할 수 있다는 말로 이해할 수 있다.

cf. CPS (Characters Per Second)

모뎀을 통해서 초당 몇 바이트(byte) 나 전송되고 있는가를 보여준다. 영문자를 기본으로 설정한 것이기 때문에 전송률을 바이트(byte : 8bit) 단위로 보면 된다. 따라서 28,800bps 모뎀의 경우는 3,600cps 의 평균 전송률을 가진다.

 

2. Bit Rate 와 Baud Rate 의 차이점

시리얼 통신 시, ASCII Code를 사용하여 통신을 할 때, 9600bps 의 통신 속도는 1200 Baud 로 표현할 수 있다. 이는 9600bit/8bit 로서 1200개의 character 로 표현된다.

그러나 Baud 는 상대적인 개념이다. 만일 Character 를 사용하지 않고 일반적인 bit 가 정보의 기본 단위라면 bit rate 는 baud rate 와 같아진다. ASCII Code 가 아니라 bit 를 정보로 받아들인다면 9600bps 는 9600 Baud 로 표현될 수 있다.

**Comment by everlong1992** [comment]
https://www.arduino.cc/en/Reference/Wire에 따르자면 MPU9250은 I2C 통신을 사용한답니다.
" This library allows you to communicate with I2C / TWI devices. On the Arduino boards with the R3 layout (1.0 pinout), the SDA (data line) and SCL (clock line) are on the pin headers close to the AREF pin. The Arduino Due has two I2C / TWI interfaces SDA1 and SCL1 are near to the AREF pin and the additional one is on pins 20 and 21. "
Uno, Ethernet	A4 (SDA), A5 (SCL) => Nano와 동일할 것 같습니다.

**Comment by seobink** [comment]
사용자로부터 "OK" 받았을때
buffer에 저장된 값 사용자에게 전달해 주는 소스 코드

buffer size length MAX = 255

전압 3.3v 일 때, 데이터 전송 끊김
전압 5v 일 때, 데이터 끊김 없이 잘됨 

```c
#include <SoftwareSerial.h>

#define rxPin 2 // 받는핀
#define txPin 3  // 보내는핀

// 내장 LED
#define ledPin 13 

// 데이터(문자열)을 받을 버퍼의 크기.
#define BUFF_SIZE 256 

//받는 문자열
String string=""; 

SoftwareSerial swSerial(txPin, rxPin); //시리얼 통신을 위한 객체선언

// 데이터 버퍼
uint8_t buffer[BUFF_SIZE];
uint8_t index = 0;
uint8_t data;

void setup() {
  Serial.begin(9600);   //시리얼모니터 
  swSerial.begin(9600);
  //  115200 
  pinMode(ledPin, OUTPUT); // ledPin = 13

  for(uint8_t i = 0; i < 26; ++i) {
          buffer[i] = i+65;
     }
     // 65~90까지 26개의 알파벳 저장
}

void loop() {
  digitalWrite(ledPin, LOW);
  
  // 데이터가 들어올때 까지 대기.
  while(!swSerial.available())
    {
      digitalWrite(ledPin, LOW);
    }
    

  while(swSerial.available()) {

    char myChar = (char)swSerial.read();  //mySerial int형식의 값을 char형식으로 변환
    string+=myChar;   //수신되는 문자열을 myString에 모두 붙임 (1바이트씩 전송되는 것을 모두 붙임)
    delay(1);           //수신 문자열 끊김 방지
    
// 9600bps 기준으로 delay 를 1ms 을 줘야 한다.

  }   


  if(!string.equals(""))  //myString 값이 있다면
  {
 //  swSerial.write("OK");
 
      if(string=="on")  //string 값이 'on' 이라면
      {
        digitalWrite(13, HIGH); //LED ON

         for(uint8_t i = 0; i < 26; ++i) {
             swSerial.write(buffer[i]);
             // 0~25까지 각각 A~Z저장되어있음
        }
       
        
      } 
   
      else {
        digitalWrite(13, LOW);  //LED OFF
      }
      
    string="";  //string 변수값 초기화
  }

 
  
}
```

**Comment by 0n33y3d-z0mb13** [comment]
12/26 진행 내용 중.. :metal:

**@seobink** 
- Serial 통신시 데이터 전송 방법은 print(), println(), write() 세가지 방법으로 가능합니다.
- print와 println은 숫자 입력시 문자열로 바꿔 전송되지만, write()함수는 **1byte,** 1개의 문자, 문자열, 배열을 출력 시에 사용합니다. (숫자 입력 시 해당하는 아스키 코드 출력)
- 그러므로 다음 코드 테스트 시 print()함수를 사용 해 보는 것도 좋을 것 같습니다.
- read()함수는 수신한 데이터를 **1byte씩** 읽어오는 함수입니다.

**@luncliff** 
- Serial 통신을 통해 PC로 데이터를 전송하는 기본적인 방법이 **Hardware serial** 방식입니다. 저희가 평소에 usb가지고 컴퓨터와 연결하여 시리얼 모니터를 출력 할 때 Serial.xxxx()와 같이 사용하는 것입니다.
- **Software serial**은 digital pin 2개(0, 1 제외 - hardware serial에서 사용)를 이용하여 Serial 통신을 하는 방법을 말합니다. 위와 같이 Serial.xxxx() 함수를 사용하지 않고 SoftwareSerial 라이브러리를 사용합니다. 블루투스 모듈은 이 방법을 사용해야 한다고 합니다.
- 해당 내용은 http://www.hardcopyworld.com/ngine/aduino/index.php/archives/1085 에 자세하게 설명되어 있습니다.

**Comment by luncliff** [comment]
### Sender
간단한 버퍼링 + 송신 코드의 예시를 이쪽에 적어놓습니다.
나중에 Classifier를 적용하면 좀 달라질 수 있겠습니다만, 그건 그때 가서 고려하겠습니다.

```c++

class Bluetooth; // Bluetooth module
class IMU;          // IMU 9250 module
struct Sample;   // ax,ay,az, gx,gy,gz ....

IMU          imu{};    
Bluetooth bt{};       

int ctr = 0;
Sample buffer[30]{};

void loop()
{
    // Step 1 : Update variable & modules
    ctr = (ctr+1) % 30;
    bt.update()     // check Bluetooth module
    imu.update()  // update from sensor register

    // Step 2 : Process input from sensor + buffering
    Sample smp = make_sample(imu);    // Read Raw data and make `Samlpe` object
    buffer[ctr] = smp; // Save to buffer

    // Step 3 : Send buffer when ready
    if(bt.ready() == true && ctr == 30)
    {
        const char* base = buffer;         // start of the array
        size_t length = sizeof(Sample) * 30;     // 30 slot
        bt.send(base, length);        // send all data to receiver
    }
}
```

### Receiver
수신측에서는 대략 이렇게 처리했으면 좋을 것이라 생각합니다. 

```c++
int main(void)
{
    while(true){
        // Read a line(30 Samples) to buffer string
        String samples = receiver.readline();
        Datetime timestamp = datetime.now();

        logfile.write(timestamp); // { "time": "2016/12/27T09:50",
        logfile.write(samples);     //  "samples" : [ {}, {}..., {} ] }
    }
    return EXIT_SUCCESS;
}

```

**Comment by 0n33y3d-z0mb13** [comment]
@luncliff 동하씨 #9 코드 확인 부탁드립니다,
