### ISSUE TITLE
IMU센서

### ISSUE THREAD

**Issue by ghost** [OliveOld/Documents#9]
# 1/7까지 센서팀
- [x] Buffer 만들기
- [x] 상보필터  적용된 코드 이해하기
- [x] matlab 설치 및 그래프 표현
- [x] 논문 계속 읽기

**Comment by ghost** [comment]
# MATLAB
- 아두이노- 매트랩 사용방법: http://www.matlabinuse.com/Arduino_with_MATLAB/10755
- 다음과 같이 그래프로 출력 되어야 함: http://m.blog.naver.com/three_letter/220427562583

**Comment by seobink** [comment]
안드로이드 스튜디오 설치 : https://developer.android.com/studio/index.html?hl=ko

**Comment by seobink** [comment]
아... git 넘나 어려운 것 ....

**Comment by 0n33y3d-z0mb13** [comment]
# 12/27 MATLAB 진행 사항(수정)

1. **아두이노 커넥트**: a = arduino('포트번호') 이용 => 안되면  a = arduino('COM3', 'Nano') 이용, 연결 완료 시 아래와 같은 내용 출력
![default](https://cloud.githubusercontent.com/assets/21700941/21492009/2fcd99d4-cc44-11e6-997d-108c76687be7.PNG)

2. **Matlab 그래프로 출력하기 위하여 코드 작성**
a. 아두이노코드 -> 01/03 진행 내용과 동일

b. Matlab코드
```
clear all;
close all;

com=serial('COM3','Baudrate',9600); %you will have different arguments

fopen(com);

n=1000;

acx=zeros(1,n);
acy=acx;
acz=acx;

f=figure(1);    % 그래프 보이게하기

for i=1:n

    ax=fscanf(com,'%e');
    ay=fscanf(com,'%e');
    az=fscanf(com,'%e');

    axis([i-40 i+40 -100 100]);

    if i>1
       % acx(1, i)=ax/1670.13; %convert to m/s^2
        %acy(1, i)=ay/1670.13; %convert to m/s^2
        %acz(1, i)=az/1670.13; %convert to m/s^2
        
        acx(1, i)=ax;
        acy(1, i)=ay;
        acz(1, i)=az;

        a(i)=line([i-1,i],[acx(i-1),acx(i)]);
        b(i)=line([i-1,i],[acy(i-1),acy(i)],'color','r');
        c(i)=line([i-1,i],[acz(i-1),acz(i)],'color','m');
        drawnow
    end   
    if i>40
        delete(a(i-40))
        delete(b(i-40))
        delete(c(i-40))
    end
    if ~ishghandle(f) 
        break             % break out of loop when figure(1) is closed
    end
end
fclose(com);
delete(com);
delete(instrfindall);
```

3. 출력됨

**Comment by 0n33y3d-z0mb13** [comment]
http://www.matlabinuse.com/index.php?mid=Mastering_MATLAB&document_srl=2512
매트랩뚜까패기

**Comment by 0n33y3d-z0mb13** [comment]
# 2017-01-03 진행 내용
1. raw값을 buffer[30]에 저장 후 블루투스 통신하는 코드 완료
```c++
#include "Wire.h"
#include "I2Cdev.h"
#include "MPU9250.h"
#include <SoftwareSerial.h>

/* 블루투스 */
#define sample_num_mdate  5000
#define rxPin 3 // 받는핀
#define txPin 2  // 보내는핀
#define ledPin 13 // 내장 LED
#define BUFF_SIZE 30 // 데이터(문자열)을 받을 버퍼의 크기.

uint8_t index = 0;
uint8_t data;
SoftwareSerial swSerial(txPin, rxPin); //시리얼 통신을 위한 객체선언
void setup_bluetooth(void);
bool ready_BT(void);


/* MPU센서 */
MPU9250 accelgyro;
I2Cdev   I2C_M;
uint8_t buffer_m[6];
struct Sample_data
{
  float s_ax, s_ay, s_az;
  float s_gx, s_gy, s_gz;
};
Sample_data buffer[30] = {0, };

// for raw data
int16_t r_ax, r_ay, r_az;
int16_t r_gx, r_gy, r_gz;

int ctrl = 0;

void setup()
{
    Wire.begin();

    /* MPU 센서 셋업 */
    accelgyro.initialize(); 

    /* 블루투스 셋업 */
    setup_bluetooth();
    //delay(1000);
}

void setup_bluetooth(void)
{
    Serial.begin(9600);   //시리얼모니터 
    swSerial.begin(9600);  //  115200 
    pinMode(ledPin, OUTPUT); // ledPin = 13
}

bool ready_BT(void)
{
  if (swSerial.available())
    return true;
  else
    return false;
}

Sample_data make_Sample(void)
{
    Sample_data smp;
    
    accelgyro.getMotion6(&r_ax, &r_ay, &r_az, &r_gx, &r_gy, &r_gz);
    
    smp.s_ax = (double) r_ax / 16384;
    smp.s_ay = (double) r_ay / 16384;
    smp.s_az = (double) r_az / 16384;

    smp.s_gx = (double) r_gx * 250 / 32768;
    smp.s_gy = (double) r_gy * 250 / 32768;
    smp.s_gz = (double) r_gz * 250 / 32768;

    return smp;  
}

void print_swSerial(Sample_data bf[])
{
  swSerial.println("Accel");
  for(int i=0; i<30; i++) {
    swSerial.print(bf[i].s_ax);
    swSerial.print(", ");
    swSerial.print(bf[i].s_ay);
    swSerial.print(", ");
    swSerial.print(bf[i].s_az);
    swSerial.print("\n");
  }
  
  swSerial.println("Gyro");
  for(int i=0; i<30; i++) {
    swSerial.print(bf[i].s_gx);
    swSerial.print(", ");
    swSerial.print(bf[i].s_gy);
    swSerial.print(", ");
    swSerial.print(bf[i].s_gz);
    swSerial.print("\n");
  }
}

void print_Serial(Sample_data bf[])
{
  for(int i=0; i<30; i++) {
    Serial.print(bf[i].s_ax);
    Serial.print(", ");
    Serial.print(bf[i].s_ay);
    Serial.print(", ");
    Serial.print(bf[i].s_az);
    Serial.print("\n");
  }
  
  for(int i=0; i<30; i++) {
    Serial.print(bf[i].s_gx);
    Serial.print(", ");
    Serial.print(bf[i].s_gy);
    Serial.print(", ");
    Serial.print(bf[i].s_gz);
    Serial.print("\n");
  }
}
void loop() 
{
    // Process input from sensor + buffering
    Sample_data smp = make_Sample();
    buffer[ctrl] = smp; // Save to buffer
    
    if( ctrl++ == 29 )
    {
        print_swSerial(buffer);
        print_Serial(buffer);
        delay(1);     // 9600bps 기준으로 delay 를 1ms 을 줘야 한다, 수신 문자열 끊김 방지
        ctrl=0;
    }
}
```
- 위 내용 출력 결과(Sketch)
![sketch](https://cloud.githubusercontent.com/assets/21700941/21603024/682c2b4e-d1dd-11e6-80ca-179f7b6face9.jpg)


2. Serial로 보낸 데이터들을 text로 저장(CoolTerm)후 그래프 출력(matlab)
 - CoolTerm 다운로드(http://freeware.the-meiers.org/)하여 text파일로 저장하면 다음과 같은 내용이 저장(Serial monitor에 출력되는 내용이 그대로 출력)
![4](https://cloud.githubusercontent.com/assets/21700941/21603092/f4b589fc-d1dd-11e6-862d-8e367a99961f.jpg)
- (matlab으로 그래프 그리기 코드 참고: http://snoopy0505.tistory.com/16) -> 진행하지 않았음
- 직접 다음 코드 작성 후 플로팅 =>  ``` data = load('test.asc'); ```
 - 다음과 같은 그래프가 출력된다. 
![matlab](https://cloud.githubusercontent.com/assets/21700941/21603007/4130b0be-d1dd-11e6-9812-6c02c552cb0f.jpg)

**Comment by 0n33y3d-z0mb13** [comment]
# 추가 진행되어야 할 사항
Calibration, Noise-filter, Complementary-filter 적용되지 않은 순수 raw data임에 주의.
관련 내용 및 코드는 #12 에 업로드 한 Position and orientation determine~에 서술되어 있음.
해당 논문에서 제공하는 코드 경로: https://github.com/LucvW/PositioningTIPS/blob/master/TIPSMPU9250.ino
matlab 코드도 등록되어 있으니 참고

**Comment by luncliff** [comment]
@everlong1992 적합하게 된 것 같습니다. master branch쪽에 코드를 커밋해주시면 제가 기존에 작성했던 shared branch 코드와 합치겠습니다.

**Comment by luncliff** [comment]
@everlong1992  @tayeon1212  필터 적용은 데이터를 획득한 이후로 미루고 진행해보는게 좋겠습니다.
Bluetooth 연결을 수행하는 C++ 코드는 작성된 상태입니다만, 윈도우에서만 쓸수 있는 코드라서 이 부분은 상의가 필요할 것 같습니다.

**Comment by seobink** [comment]
@everlong1992 @tayeon1212 기기 쪽에 올려야할 코드를 ZIP파일로 해서 올려주심 감사하겠습니다

**Comment by luncliff** [comment]
@seobink [이 코드](https://github.com/OliveOld/PetTrack/blob/master/src/IMU1.ino)입니다.

**Comment by 0n33y3d-z0mb13** [comment]
# 2017-01-09 진행 사항
해야 할 것: 가속도계, 자이로 Off-set 조정, 두 값을 취합(다음 주 까지), 그래프 분석하여 보완 할 점 추가
다음주에 안양 방문 예정

**Comment by 0n33y3d-z0mb13** [comment]
# SMA(Signal Magnitude Area)/SVM(Signal Vector Magntude)
[3축 가속도를 이용한 활동상태 분류 시스템 구현 및 알고리즘 개발.pdf](https://github.com/OliveOld/Documents/files/705758/3.pdf)
[3축 가속도 센서를 이용한 실시간 걸음 수 검출 알고리즘.pdf](https://github.com/OliveOld/Documents/files/705759/3.pdf)
[3축 가속도 센서를 이용한 배례동작 모니터링 및 자동검출 시스템 설계.pdf](https://github.com/OliveOld/Documents/files/705760/3.pdf)
